parameters:
    angel_garrido.twig.bootstrap_form_extension.class: AngelGarrido\CrudGeneratorBundle\Twig\BootstrapFormExtension

services:
    angel_garrido.twig.bootstrap_form_extension:
        class: %angel_garrido.twig.bootstrap_form_extension.class%
        tags:
            - { name: twig.extension }